"""Runs every synthetic dataset in fixtures/synthetic_datasets.py through the
full engine end-to-end — scoring, LLM remediation, report — and writes each
result to docs/demo_reports/<slug>.md.

This is the first real integration test of the whole pipeline with a live
LLM in the loop, and it's the demo material asked for in ROADMAP.md
Checkpoint 3: something to show what the tool actually produces, without
needing the frontend or any real ACE/TASO data.

Usage: python scripts/run_demo_assessment.py
Needs LLM_BASE_URL/LLM_MODEL configured in .env (defaults to the vLLM
endpoint — see app/config.py for why that's the default over local Ollama).
"""

import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from app.adapters.fair.adapter import FairAdapter
from app.adapters.fair.prompt import PROMPT_VERSION, render_remediation_prompt
from app.config import settings
from app.engine.models import Answer, AssessmentRun
from app.engine.remediation import write_remediation
from app.engine.report import build_report_markdown

from fixtures.synthetic_datasets import SYNTHETIC_DATASETS

_OUTPUT_DIR = Path(__file__).parent.parent.parent / "docs" / "demo_reports"


def run_one(dataset: dict, adapter: FairAdapter) -> None:
    run = AssessmentRun(adapter_id=adapter.adapter_id, subject_label=dataset["subject_label"])
    indicators_by_id = {q.indicator.id: q.indicator for q in adapter.question_set()}

    findings = []
    remediations_by_finding_id = {}
    remediation_count = 0

    for indicator_id, raw in dataset["answers"].items():
        indicator = indicators_by_id[indicator_id]
        answer = Answer(
            run_id=run.id,
            indicator_id=indicator_id,
            raw_answer={"value": raw["value"], "label": raw["label"]},
            free_text_note=raw["note"],
            is_dont_know=(raw["value"] == "dont_know"),
        )
        finding = adapter.score(indicator, answer)
        findings.append(finding)

        if finding.severity != "pass":
            prompt = render_remediation_prompt(indicator=indicator, answer=answer, subject_label=dataset["subject_label"])
            draft = write_remediation(
                finding=finding, answer=answer, prompt=prompt, prompt_version=PROMPT_VERSION
            )
            remediations_by_finding_id[str(finding.id)] = draft
            remediation_count += 1
            flag = "" if draft.grounding_check_passed else "  [grounding check FAILED: " + str(draft.grounding_check_notes) + "]"
            print(f"    {indicator.title[:45]:45s} -> {finding.severity:10s}{flag}")

    markdown, score = build_report_markdown(
        findings=findings, indicators_by_id=indicators_by_id, remediations_by_finding_id=remediations_by_finding_id
    )

    header = (
        f"# {dataset['subject_label']}\n\n"
        f"**Format:** {dataset['format']}  \n"
        f"**Size:** {dataset['size']}  \n"
        f"**Domain:** {dataset['domain']}  \n"
        f"**Description:** {dataset['description']}\n\n"
        f"*Generated by scripts/run_demo_assessment.py against `{settings.llm_model}` "
        f"({settings.llm_base_url}). This is synthetic demo data — see fixtures/synthetic_datasets.py "
        f"and ROADMAP.md Checkpoint 3 for why.*\n\n---\n\n"
    )

    _OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    output_path = _OUTPUT_DIR / f"{dataset['slug']}.md"
    output_path.write_text(header + markdown, encoding="utf-8")

    print(f"  Score: {score}/100 | {remediation_count} findings remediated | -> {output_path.relative_to(_OUTPUT_DIR.parent.parent)}")


def main() -> None:
    adapter = FairAdapter()
    print(f"Running {len(SYNTHETIC_DATASETS)} synthetic datasets against {settings.llm_model} @ {settings.llm_base_url}\n")

    for dataset in SYNTHETIC_DATASETS:
        print(f"--- {dataset['subject_label']} ---")
        start = time.time()
        run_one(dataset, adapter)
        print(f"  ({time.time() - start:.1f}s)\n")


if __name__ == "__main__":
    main()
