"""add plan caching and step-scoped mentor

Revision ID: b9aa2d13f2f5
Revises: 3a9862e9560f
Create Date: 2026-08-25 22:02:48.433502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel-typed columns (e.g. AutoString) need this import;
                 # autogenerate's own imports block doesn't reliably add it.


# revision identifiers, used by Alembic.
revision: str = 'b9aa2d13f2f5'
down_revision: Union[str, None] = '3a9862e9560f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('goal', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['assessmentrun.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planstep',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('detail', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planstepindicator',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plan_step_id', sa.Uuid(), nullable=False),
    sa.Column('indicator_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicator.id'], ),
    sa.ForeignKeyConstraint(['plan_step_id'], ['planstep.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # server_default lets this NOT NULL column land on a table that already
    # has rows (real completed assessments from before this migration) --
    # they're all treated as needing a fresh plan, which is correct: none of
    # them have ever had one.
    op.add_column(
        'assessmentrun', sa.Column('plan_stale', sa.Boolean(), nullable=False, server_default=sa.true())
    )

    # Existing mentor conversations/messages predate step-scoping and have
    # no plan step to point at -- dev-only test data from earlier manual
    # testing this session (see docs/DECISIONS.md / devlog/HANDOFF.md),
    # never real ACE data, and the dev branch is already treated as freely
    # resettable. Clearing them first lets plan_step_id be added as a plain
    # NOT NULL column instead of needing a fabricated backfill value.
    op.execute('DELETE FROM mentormessage')
    op.execute('DELETE FROM mentorconversation')

    op.add_column('mentorconversation', sa.Column('plan_step_id', sa.Uuid(), nullable=False))
    op.drop_constraint(op.f('uq_mentorconversation_run_indicator'), 'mentorconversation', type_='unique')
    op.create_unique_constraint('uq_mentorconversation_run_planstep', 'mentorconversation', ['run_id', 'plan_step_id'])
    op.drop_constraint(op.f('mentorconversation_indicator_id_fkey'), 'mentorconversation', type_='foreignkey')
    op.create_foreign_key(None, 'mentorconversation', 'planstep', ['plan_step_id'], ['id'])
    op.drop_column('mentorconversation', 'indicator_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mentorconversation', sa.Column('indicator_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'mentorconversation', type_='foreignkey')
    op.create_foreign_key(op.f('mentorconversation_indicator_id_fkey'), 'mentorconversation', 'indicator', ['indicator_id'], ['id'])
    op.drop_constraint('uq_mentorconversation_run_planstep', 'mentorconversation', type_='unique')
    op.create_unique_constraint(op.f('uq_mentorconversation_run_indicator'), 'mentorconversation', ['run_id', 'indicator_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('mentorconversation', 'plan_step_id')
    op.drop_column('assessmentrun', 'plan_stale')
    op.drop_table('planstepindicator')
    op.drop_table('planstep')
    op.drop_table('plan')
    # ### end Alembic commands ###
