"""baseline: schema as of mentor POC start

Revision ID: fd7648a1773b
Revises:
Create Date: 2026-08-25 18:47:42.109694

This migration originally had an empty upgrade() (a bare `pass`) -- it was
authored against a database that already had these tables from the pre-
Alembic SQLModel.metadata.create_all() workflow, so "upgrade" meant nothing
needed to change there. That's fine for the one database it was written
against, but it makes this migration chain incapable of bootstrapping a
genuinely fresh database (e.g. a new Neon branch for an actual deploy,
Checkpoint 7) -- `alembic upgrade head` from empty would skip straight to
later migrations that ALTER or foreign-key into tables (assessmentrun,
indicator, etc.) that were never created. Caught in review before promoting
past development; filled in with the actual baseline schema, generated by
running autogenerate against a truly empty database with the pre-mentor-POC
model set (git commit 4b06bd1, the last point before Checkpoint 9's tables
were added) -- not hand-transcribed, to avoid a subtly wrong column/type.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel-typed columns (e.g. AutoString) need this import;
                 # autogenerate's own imports block doesn't reliably add it.


# revision identifiers, used by Alembic.
revision: str = 'fd7648a1773b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adapter',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assessmentrun',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('adapter_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subject_label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_by_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['adapter_id'], ['adapter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('indicator',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('adapter_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('external_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('principle_group', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('definition', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('plain_language_question', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('help_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('example', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('priority', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('scoring_rubric', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['adapter_id'], ['adapter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answer',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('indicator_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('raw_answer', sa.JSON(), nullable=True),
    sa.Column('free_text_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_dont_know', sa.Boolean(), nullable=False),
    sa.Column('answered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicator.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['assessmentrun.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'indicator_id', name='uq_answer_run_indicator')
    )
    op.create_table('report',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('summary_score', sa.Float(), nullable=False),
    sa.Column('rendered_markdown', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['assessmentrun.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_table('finding',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('indicator_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('answer_id', sa.Uuid(), nullable=False),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('priority_weight', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answer.id'], ),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicator.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['assessmentrun.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'indicator_id', name='uq_finding_run_indicator')
    )
    op.create_table('remediationdraft',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('finding_id', sa.Uuid(), nullable=False),
    sa.Column('llm_model_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('remediation_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('grounding_check_passed', sa.Boolean(), nullable=False),
    sa.Column('grounding_check_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('shown_to_user_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['finding_id'], ['finding.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('remediationdraft')
    op.drop_table('finding')
    op.drop_table('report')
    op.drop_table('answer')
    op.drop_table('indicator')
    op.drop_table('assessmentrun')
    op.drop_table('adapter')
    # ### end Alembic commands ###
