"""Report generation and caching. Generating a report calls the LLM once
per weak/unknown finding, so it's generated exactly once per run and
persisted (a Report row) — every later GET returns the cached result,
never re-calling the LLM. Use the regenerate endpoint to force one finding
to be redone.
"""

import time
from uuid import UUID

from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.exc import IntegrityError
from sqlmodel import Session, select

from app.adapters.registry import get_adapter
from app.api.schemas import FindingOut, ReportOut
from app.db import get_session
from app.engine.models import Answer, AssessmentRun, Finding, Indicator, RemediationDraft, Report
from app.engine.remediation import write_remediation
from app.engine.report import build_report_markdown

router = APIRouter(prefix="/assessments", tags=["report"])

# How long a losing concurrent request waits for the winner to finish a real
# generation pass (multiple sequential LLM calls, easily 10-60s) before
# giving up. Findings/RemediationDrafts/Report all carry unique constraints
# on run_id (+ indicator_id where relevant), so only one concurrent caller's
# writes can ever succeed for a given run — this wait is what lets the loser
# return the winner's result instead of erroring the instant it detects the
# conflict, which is well before the winner has actually finished.
_GENERATION_WAIT_POLL_SECONDS = 0.5
_GENERATION_WAIT_MAX_SECONDS = 90


def _report_exists(session: Session, run_id: UUID) -> bool:
    return session.exec(select(Report).where(Report.run_id == run_id)).first() is not None


def _generate_report(session: Session, run: AssessmentRun) -> None:
    try:
        _do_generate_report(session, run)
        return
    except IntegrityError:
        session.rollback()

    waited = 0.0
    while waited < _GENERATION_WAIT_MAX_SECONDS:
        if _report_exists(session, run.id):
            return
        time.sleep(_GENERATION_WAIT_POLL_SECONDS)
        waited += _GENERATION_WAIT_POLL_SECONDS

    raise HTTPException(
        status_code=503,
        detail="This report is still being generated by a concurrent request. Try again in a few seconds.",
    )


def _do_generate_report(session: Session, run: AssessmentRun) -> None:
    adapter = get_adapter(run.adapter_id)
    answers = session.exec(select(Answer).where(Answer.run_id == run.id)).all()
    indicator_ids = [a.indicator_id for a in answers]
    indicators = session.exec(select(Indicator).where(Indicator.id.in_(indicator_ids))).all()
    indicators_by_id = {i.id: i for i in indicators}
    answers_by_indicator_id = {a.indicator_id: a for a in answers}

    missing_indicators = set(indicator_ids) - set(indicators_by_id)
    if missing_indicators:
        raise HTTPException(
            status_code=500,
            detail=(
                f"Indicator rows not found in the database for: {sorted(missing_indicators)}. "
                "Has scripts/seed_indicators.py been run against this database?"
            ),
        )

    findings: list[Finding] = []
    for answer in answers:
        indicator = indicators_by_id[answer.indicator_id]
        finding = adapter.score(indicator, answer)
        session.add(finding)
        findings.append(finding)
    session.commit()
    for f in findings:
        session.refresh(f)

    # Every finding gets written up now, not just weak ones -- a passing
    # indicator gets a short "why this is fine" note instead of a fix, so the
    # report never just shows a bare title with no explanation.
    remediations_by_finding_id: dict[str, RemediationDraft] = {}
    for finding in findings:
        indicator = indicators_by_id[finding.indicator_id]
        answer = answers_by_indicator_id[finding.indicator_id]
        prompt = adapter.render_remediation_prompt(
            indicator=indicator, answer=answer, subject_label=run.subject_label, severity=finding.severity
        )
        draft = write_remediation(finding=finding, answer=answer, prompt=prompt, prompt_version=adapter.prompt_version)
        session.add(draft)
        remediations_by_finding_id[str(finding.id)] = draft
    session.commit()

    markdown, score = build_report_markdown(
        findings=findings, indicators_by_id=indicators_by_id, remediations_by_finding_id=remediations_by_finding_id
    )
    session.add(Report(run_id=run.id, summary_score=score, rendered_markdown=markdown))
    session.commit()


def _latest_remediation_by_finding_id(session: Session, finding_ids: list) -> dict:
    # Ordered oldest-first so the dict comprehension below ends up with the
    # MOST RECENT draft per finding — regenerate_finding() (and a revisited
    # answer, see _rescore_finding_and_refresh_report) adds a new draft
    # rather than replacing the old one, so a finding can have several.
    # Without this order_by, which draft "wins" here is whatever order
    # SQLite happens to return (unspecified without ORDER BY), which could
    # silently show a stale regeneration instead of the latest one.
    #
    # Keyed by str(finding_id) -- build_report_markdown() (engine/report.py)
    # looks up by str(f.id), not the raw UUID, so this has to match that
    # contract or every finding's remediation would silently look missing
    # when this dict is handed to it.
    remediations = (
        session.exec(
            select(RemediationDraft)
            .where(RemediationDraft.finding_id.in_(finding_ids))
            .order_by(RemediationDraft.generated_at)
        ).all()
        if finding_ids
        else []
    )
    return {str(r.finding_id): r for r in remediations}


def _rescore_finding_and_refresh_report(session: Session, run: AssessmentRun, indicator_id: str, answer: Answer) -> None:
    """Called from routes_answers.py when someone revisits and changes an
    answer on a run that's already completed and reported. Marks any saved
    plan stale unconditionally (cheap, and always correct to do). Keeps the
    report honest without a full 12-call regeneration: re-scores and
    re-writes remediation for just the one indicator that changed, then
    recomputes the cached score from all current findings -- but that part
    is a no-op if no Report exists yet for this run (nothing cached to go
    stale there)."""
    # A revisited answer can change which findings are open, so any saved
    # FAIRification plan (routes_plan.py) is now potentially out of date too
    # -- not patched in place (that's a full re-synthesis, not a one-field
    # edit like the report), just flagged so the next GET /plan regenerates
    # a fresh version instead of serving the stale one.
    run.plan_stale = True
    session.add(run)
    session.commit()

    report = session.exec(select(Report).where(Report.run_id == run.id)).first()
    if report is None:
        return

    adapter = get_adapter(run.adapter_id)
    indicator = session.get(Indicator, indicator_id)
    finding = session.exec(
        select(Finding).where(Finding.run_id == run.id, Finding.indicator_id == indicator_id)
    ).first()
    if indicator is None or finding is None:
        return

    rescored = adapter.score(indicator, answer)
    finding.severity = rescored.severity
    finding.priority_weight = rescored.priority_weight
    session.add(finding)
    session.commit()
    session.refresh(finding)

    try:
        prompt = adapter.render_remediation_prompt(
            indicator=indicator, answer=answer, subject_label=run.subject_label, severity=finding.severity
        )
        draft = write_remediation(finding=finding, answer=answer, prompt=prompt, prompt_version=adapter.prompt_version)
        session.add(draft)
        session.commit()
    except Exception:
        # Deliberately swallowed: this function is called from an answer
        # PUT whose primary job (saving the answer) already succeeded and
        # committed above. An LLM/network failure here shouldn't turn a
        # successful save into a 500 -- the caller only wanted to record
        # their answer, not necessarily wait on a live model call. The
        # finding's severity (just committed) is still correct; only its
        # remediation text is left showing the previous draft until a
        # successful regenerate or another revisit.
        pass

    all_findings = session.exec(select(Finding).where(Finding.run_id == run.id)).all()
    all_indicators = session.exec(
        select(Indicator).where(Indicator.id.in_({f.indicator_id for f in all_findings}))
    ).all()
    indicators_by_id = {i.id: i for i in all_indicators}
    remediations_by_finding_id = _latest_remediation_by_finding_id(session, [f.id for f in all_findings])

    markdown, score = build_report_markdown(
        findings=all_findings, indicators_by_id=indicators_by_id, remediations_by_finding_id=remediations_by_finding_id
    )
    report.summary_score = score
    report.rendered_markdown = markdown
    session.add(report)
    session.commit()


def _load_report_out(session: Session, run_id: UUID) -> ReportOut:
    report = session.exec(select(Report).where(Report.run_id == run_id)).first()
    if report is None:
        raise HTTPException(status_code=500, detail="Report generation did not produce a Report row")

    findings = session.exec(select(Finding).where(Finding.run_id == run_id)).all()
    finding_ids = [f.id for f in findings]
    remediation_by_finding_id = _latest_remediation_by_finding_id(session, finding_ids)

    indicator_ids = {f.indicator_id for f in findings}
    indicators = (
        session.exec(select(Indicator).where(Indicator.id.in_(indicator_ids))).all() if indicator_ids else []
    )
    indicators_by_id = {i.id: i for i in indicators}

    findings_out = [
        FindingOut(
            indicator_id=f.indicator_id,
            title=indicators_by_id[f.indicator_id].title,
            severity=f.severity,
            principle_group=indicators_by_id[f.indicator_id].principle_group,
            remediation_text=remediation_by_finding_id[str(f.id)].remediation_text
            if str(f.id) in remediation_by_finding_id
            else None,
        )
        for f in sorted(findings, key=lambda f: indicators_by_id[f.indicator_id].display_order)
    ]

    return ReportOut(
        run_id=run_id,
        score=report.summary_score,
        generated_at=report.generated_at,
        findings=findings_out,
        markdown=report.rendered_markdown,
    )


@router.get("/{run_id}/report", response_model=ReportOut)
def get_report(run_id: UUID, session: Session = Depends(get_session)) -> ReportOut:
    run = session.get(AssessmentRun, run_id)
    if run is None:
        raise HTTPException(status_code=404, detail="Assessment not found")
    if run.status != "completed":
        raise HTTPException(status_code=400, detail="Assessment must be completed before a report can be generated")

    already_generated = session.exec(select(Report).where(Report.run_id == run_id)).first() is not None
    if not already_generated:
        _generate_report(session, run)

    return _load_report_out(session, run_id)


@router.post("/{run_id}/findings/{indicator_id}/regenerate", response_model=FindingOut)
def regenerate_finding(run_id: UUID, indicator_id: str, session: Session = Depends(get_session)) -> FindingOut:
    run = session.get(AssessmentRun, run_id)
    if run is None:
        raise HTTPException(status_code=404, detail="Assessment not found")

    finding = session.exec(
        select(Finding).where(Finding.run_id == run_id, Finding.indicator_id == indicator_id)
    ).first()
    if finding is None:
        raise HTTPException(status_code=404, detail="Finding not found — generate the report first")

    answer = session.exec(
        select(Answer).where(Answer.run_id == run_id, Answer.indicator_id == indicator_id)
    ).first()
    indicator = session.get(Indicator, indicator_id)
    if answer is None or indicator is None:
        raise HTTPException(status_code=500, detail="Answer or indicator missing for an existing finding")

    adapter = get_adapter(run.adapter_id)
    prompt = adapter.render_remediation_prompt(
        indicator=indicator, answer=answer, subject_label=run.subject_label, severity=finding.severity
    )
    draft = write_remediation(finding=finding, answer=answer, prompt=prompt, prompt_version=adapter.prompt_version)
    session.add(draft)
    session.commit()

    return FindingOut(
        indicator_id=indicator_id,
        title=indicator.title,
        severity=finding.severity,
        principle_group=indicator.principle_group,
        remediation_text=draft.remediation_text,
    )
